apiVersion: v1
kind: Service
metadata:
  name: nelly-lux-front-service
spec:
  type: LoadBalancer
  selector:
    app: nelly-lux-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
